### ISSUE TITLE
Отключить react/prefer-stateless-function

### ISSUE THREAD

**Issue by nezed** [kupibilet-frontend/eslint-config-kupibilet#14]
Правило [`react/prefer-stateless-function`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/prefer-stateless-function.md) режет и `PureComponent`'ы, без стейта.
В актуальных версиях реакта, `stateless` компоненты перерисовываются **всегда**, когда изменяется их родитель (поскольку все понимают что внутри `stateless` может быть не-`PureComponent`, это поведение скорее всего сохранится)

Предлагаю:
1) Изменить параметры правила на 
```
    prefer-stateless-function:
        - error
        - ignorePureComponents: true
```

2) Отключить правило вовсе

**Comment by 7rulnik** [comment]
Я за 1 вариант
