### ISSUE TITLE
Доработать object-curly-newline

### ISSUE THREAD

**Issue by nezed** [kupibilet-frontend/eslint-config-kupibilet#44]
1. Увеличить количество свойств как минимум до 6
```js
  object-curly-newline:
    - error
    -
      minProperties: 6
      multiline: true
      consistent: true
```
2. Запретить ситуацию 
```javascript
import {
  createStack, createFetch, method, base, accept, parse, header, json,
} from 'http-client'
```

**Comment by yulya9060** [comment]
1. поправлено в PR https://github.com/kupibilet-frontend/eslint-config-kupibilet/pull/51
2. на данный момент нет правила для импорта, есть вот такое обсуждение: https://github.com/eslint/eslint/pull/9563

**Comment by nezed** [comment]
Resolved with #51
