### ISSUE TITLE
Ограничить операторы до/после которых может быть newline в выражениях

### ISSUE THREAD

**Issue by nezed** [kupibilet-frontend/eslint-config-kupibilet#45]
Исключить ситуацию 
```javascript
        flights.some((trip) => trip.a ===
          trip.b)
```
Запретить делать разрывы в выражениях с операторами `==` и `===` (и, возможно ещё какими-то)

Разрешены:
```js
const a = x
  ? b
  : c
```

```js
const a = x
  || (b && c)
  || (d && e)
```

```js
const a = x
  && a
  && b
```

При наличии в выражении newline - оператор всегда должен начинать следующую строку

**Comment by yulya9060** [comment]
https://github.com/kupibilet-frontend/eslint-config-kupibilet/pull/52
