### ISSUE TITLE
TypeError: Cannot read property 'range' of null

### ISSUE THREAD

**Issue by nezed** [kupibilet-frontend/eslint-config-kupibilet#48]
Чтобы исправить преследующую, глупую ошибку 
https://travis-ci.org/kupibilet-frontend/ui/builds/522992259

Было сделано #47 , что не есть хорошо. Как и сама преследующая ошибка 

- https://stackoverflow.com/questions/42978761/babel-eslint-typeerror-cannot-read-property-range-of-null
- https://github.com/babel/babel-eslint/issues/530

**Comment by loonywizard** [comment]
В результате проведённых исследований выявили, что проблема кроется в модуле  `@babel/types`, старую версию которого используют некоторые зависимости

Решением является явное указание версии пакета `@babel/types` в проектах, в которых используется `eslint-config-kupibilet` 

Версия, которую стоит указывать: `7.4.4`

**Comment by loonywizard** [comment]
в рамках задачи добавил изменения в следующие проекты
https://gitlab.amazon/frontend/widgets/merge_requests/96
https://gitlab.amazon/frontend/kupibilet.ru/merge_requests/1859

зафиксировал старую версию в следующих репозиториях и решил обновить `eslint-config-kupibilet` в слудующих местах
https://gitlab.amazon/backend/lpc.amazon/merge_requests/27

**Comment by nezed** [comment]
Остановились на 
```json
  "resolutions": {
    "@babel/types": "7.4.4"
  },
```

всё помёржил
